const LOGIN = 'LOGIN';
const LOGIN_PENDING = 'LOGIN_PEDING';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FALSE = 'LOGIN_FALSE';

const GET_USER_PENDING = 'GET_USER_PENDING';
const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
const GET_USER_FALSE = 'GET_USER_FALSE';

export {
  LOGIN,
  LOGIN_PENDING,
  LOGIN_SUCCESS,
  LOGIN_FALSE,
  GET_USER_PENDING,
  GET_USER_SUCCESS,
  GET_USER_FALSE,
};
